### ISSUE TITLE
Transition to giving users hack.club urls instead of hack.af urls

### ISSUE THREAD

**Issue by grymmy** [hackclub/hack.af#100]
NOTE - we must continue to support hack.af links as they are omnipresent in our current marketing and social media presence - however, we should transition to giving out hack.club links by default using the hack.af CLI.

See screenshots below - all occurrences of hack.af should be replaced with hack.club 
![Screenshot 2024-05-02 at 10 36 58 AM](https://github.com/hackclub/hack.af/assets/43505167/8ed17ed6-2b26-436f-9a5c-d0ee5624e705)

**Comment by DevIos01** [comment]
PR has been merged for this https://github.com/hackclub/hack.af/pull/106 so i am closing the issue.

feel free to reopen the issue if any updates are needed on it 🫡
