### ISSUE TITLE
Analytics on plausible.io

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack.af#33]
Currently all hits are tracked in airtable, but records have to get cleared after 50k rows. It'd be nice to have this log to something like plausible.io that doesn't have a hard limit on number of logs.

**Comment by itsmingjie** [comment]
Happy to help 😛 Is there a Plausible instance/key that I should send to?

**Comment by maxwofford** [comment]
Yeah, thanks!

```
<script defer data-domain="hack.af" src="https://plausible.io/js/script.js"></script>
```

**Comment by grymmy** [comment]
The implementation of this should probably be done using the [event endpoint](https://plausible.io/docs/events-api).

**Comment by grymmy** [comment]
Closing this as we monitor hack.af using grafana
