### ISSUE TITLE
https://go.mingjie.info/template is not working

### ISSUE THREAD

**Issue by Shrey-Mehra** [hackclub/hack.af#36]
![image](https://github.com/hackclub/hack.af/assets/85977707/57828098-c269-4768-a9c0-ee8a15c1d36a)

**Comment by itsmingjie** [comment]
This will be closed by #35 once we move off of using AirTable.

**Comment by Shrey-Mehra** [comment]
ok thanks @itsmingjie for the update

**Comment by sampoder** [comment]
We're now on Postgres - thank you for flagging & closing
