### ISSUE TITLE
Instrument bot operations

### ISSUE THREAD

**Issue by grymmy** [hackclub/hack.af#40]
Add metrics reporting to the bot operations so that we can monitor them in grafana

**Comment by recursiveforte** [comment]
has this been resolved?

**Comment by grymmy** [comment]
> has this been resolved?

Nope, not yet.

**Comment by DevIos01** [comment]
Added support to trigger of :

botcommands.${args[0]}.attempt
botcommands.${args[0]}.success
botcommands.${args[0]}.error
lookup.cache.hit
lookup.cache.miss
http.responses
