### ISSUE TITLE
Multiple versions of the same slug are created

### ISSUE THREAD

**Issue by grymmy** [hackclub/hack.af#49]
It appears that the functionality that hack.af provides to update slugs has faulty logic.  Multiple rows end up being added to the database related to the same slug (should never happen).

Evidence:
<img width="767" alt="Screenshot 2023-08-21 at 3 20 18 PM" src="https://github.com/hackclub/hack.af/assets/43505167/7e5d675f-f4f2-4d28-9741-f4367e88b15d">

**Comment by recursiveforte** [comment]
wahoo
