### ISSUE TITLE
/hack.af shorten doesn't show URL

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack.af#65]
After running `/hack.af shorten gooogle.com` (an invalid URL), my command is hidden and the result data doesn't show. We should probably have something saying "this goes to X" so I can quickly tell what shortlink I made.

<img width="534" alt="Screenshot 2023-09-08 at 11 44 34" src="https://github.com/hackclub/hack.af/assets/5891442/4eefaf0d-54b1-4506-a87b-13bc1a9a18b3">

**Comment by grymmy** [comment]
Proposed (specific, TLDR) copy change:

Instead of
`Your short URL: [hack.af/kpo6wu](https://hack.af/kpo6wu)`
change it to:
`Your short URL: [hack.af/kpo6wu](https://hack.af/kpo6wu)  ->  google.com`

**Comment by DevIos01** [comment]
![image](https://github.com/hackclub/hack.af/assets/34939959/3376e607-adc1-4c00-92ba-b0de3c1b2590)

Updated and it's live in production!
