### ISSUE TITLE
/hack.af set doesn't confirm or warn before overwriting links

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack.af#66]
I just overwrote an existing slug by setting a new value. /hack.af didn't warn me that I was overwriting data and didn't show the previous value:

<img width="400" alt="Screenshot 2023-09-08 at 11 50 40" src="https://github.com/hackclub/hack.af/assets/5891442/730f5476-fb24-47c0-a9c4-56b3df3f39e2">

**Comment by grymmy** [comment]
I think a reasonable thing to do to ameliorate this is to make clear to the user what the old value was when overwriting it.  We also know we want to have an audit log of changes, which could allow us to easily implement an "undo" operation (and also we will be able to [see the history](https://github.com/hackclub/hack.af/issues/69)).

**Comment by DevIos01** [comment]
Chnages as @grymmy said is live and it should work out!
