### ISSUE TITLE
Unclear what's an admin-only command

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack.af#67]
As an admin running the help command I get an awesome list of tools:

<img width="417" alt="Screenshot 2023-09-08 at 11 57 59" src="https://github.com/hackclub/hack.af/assets/5891442/747607c3-5978-4ca6-9e07-0f2fc740b010">

Only thing is I'd assume everyone has access to these because I see them (which is untrue– I have the admin set of access). Maybe we can indicate the admin-only commands so I don't tell people to use these commands themselves?

**Comment by grymmy** [comment]
Specific copy proposal:
Instead of:
`/hack.af delete [slug-name]: Delete a slug from the database.`
add bold warning:
`/hack.af delete [slug-name]: (**Admin only**) Delete a slug from the database.`

**Comment by DevIos01** [comment]
old:
![image](https://github.com/hackclub/hack.af/assets/34939959/e98f993a-44e1-4feb-a2ab-584a0247a846)

new after changes:
![image](https://github.com/hackclub/hack.af/assets/34939959/785d1cc3-35ed-48b5-9fc6-b3d42927e576)
