### ISSUE TITLE
Create new command to show change history for a slug

### ISSUE THREAD

**Issue by grymmy** [hackclub/hack.af#69]
Usage: /hack.af history <slug>
Description: This command would show all changes made over time to a slug.  It will show the times when the slugs changed, what the slug URLs were during that period of time.  It should also show, interleaved and respecting time, [all notes](https://github.com/hackclub/hack.af/issues/59) added.

**Comment by DevIos01** [comment]
Completed!, waiting for @grymmy approval / changes.

**Comment by DevIos01** [comment]
Completed and live!
