### ISSUE TITLE
Create new admin command to retrieve analytics/metrics

### ISSUE THREAD

**Issue by grymmy** [hackclub/hack.af#70]
Command: /hack.af metrics [slug]
Description: This command should retrieve all information from the "Log" table associated with a slug and display it to the user.

**Comment by DevIos01** [comment]
[this change](https://github.com/hackclub/hack.af/commit/e2c045aee8106141aa62e3ba12afde57ffe305f4) complete the task, waiting on @grymmy to check into it and see what should be available on those metrics

**Comment by DevIos01** [comment]
Completed and livo 👍
