### ISSUE TITLE
Make help better for all commands

### ISSUE THREAD

**Issue by grymmy** [hackclub/hack.af#72]
All commands should have good help documentation built-in, including required/optional parameters.

What it looks like now:
![Screenshot 2023-10-12 at 10 12 38 AM](https://github.com/hackclub/hack.af/assets/43505167/aea46807-94c5-4141-83a6-5eebdef38a9c)

Example of what one should look like:
`/hack.af set [slug-name] [destination-url]`

**Comment by DevIos01** [comment]
Completed and it's live in prod! 👍
