### ISSUE TITLE
Counter does not increment after navigating to a slug

### ISSUE THREAD

**Issue by grymmy** [hackclub/hack.af#73]
Steps to reproduce:
1. Create a new slug
2. Navigate to the slug in your browser.
3. Run /hack.af metrics graham_test.  Observe Counter:1
4. Navigate to the slug again in your browser.
5. Run /hack.af metrics graham_test.

Expected result: Observe Counter: 2
Actual result: Observe Counter: 1

**Comment by DevIos01** [comment]
![image](https://github.com/hackclub/hack.af/assets/34939959/281a78cb-f809-4134-a387-4722e3056655)

works fine with new changes!
