### ISSUE TITLE
Error processing request for history for old slugs

### ISSUE THREAD

**Issue by grymmy** [hackclub/hack.af#74]
`/hack.af history onboard`  shows:
![Screenshot 2023-10-12 at 10 28 30 AM](https://github.com/hackclub/hack.af/assets/43505167/99a070d1-9f96-4ac9-b403-aac8b3373d30)

**Comment by DevIos01** [comment]
should be fixed, if it doesn't exist on Slughistory it will ask on logs and show the result which makes it backend compatibility to old slugs

![image](https://github.com/hackclub/hack.af/assets/34939959/f21be736-9a63-4e13-93be-4fcab0eb6d16)
