### ISSUE TITLE
Running /hack.af note without parameters causes error

### ISSUE THREAD

**Issue by grymmy** [hackclub/hack.af#75]
Steps to reproduce:
1. Run `/hack.af note`

Expected behavior: A warning error saying invalid params
Actual behavior: 
![Screenshot 2023-10-12 at 10 38 10 AM](https://github.com/hackclub/hack.af/assets/43505167/4491af77-ab9f-403f-90f9-58f90a08df43)

**Comment by DevIos01** [comment]
Fixed and it works perfecto now!

![image](https://github.com/hackclub/hack.af/assets/34939959/da3ba4f0-a78c-40bd-abab-1415b0f6bc8e)
