### ISSUE TITLE
Search command fails

### ISSUE THREAD

**Issue by grymmy** [hackclub/hack.af#76]
Steps to reproduce:
1. /hack.af search hack
Expected behavior: no crash
Actual behavior: 
<img width="494" alt="Screenshot 2023-10-13 at 11 46 36 AM" src="https://github.com/hackclub/hack.af/assets/43505167/5d45a036-8a02-44a6-b91a-d3c77e115089">

**Comment by DevIos01** [comment]
Fixed, added better error so it's understandable

![image](https://github.com/hackclub/hack.af/assets/34939959/a11ad191-dab2-4ca5-a4e9-6f895b5b32a3)
