### ISSUE TITLE
Error when attempting history on newly created slug

### ISSUE THREAD

**Issue by grymmy** [hackclub/hack.af#77]
Steps to reproduce:
1. /hack.af shorten https://google.com
2. /hack.af history <newly-created-slugid>
Expected result: Valid history displayed
Actual result: There was an error processing your request: Request failed with status code 500

**Comment by DevIos01** [comment]
With the recent fix of #78, this is also fixed

Reason: A recent fix for #73, broke the SQL syntax which is now fixed and works fine

Result:
![image](https://github.com/hackclub/hack.af/assets/34939959/06a057e8-acc2-4e71-bdd1-9d4ff87da6d9)
