### ISSUE TITLE
Metrics does not display timestamp, slug or url for newly created slug

### ISSUE THREAD

**Issue by grymmy** [hackclub/hack.af#78]
Steps to reproduce:
1. /hack.af shorten https://google.com
2. /hack.af metrics <new-slug>
Expected result: Timestamp, slug and URL are visible in output
Actual result: 
<img width="223" alt="Screenshot 2023-10-16 at 9 08 42 AM" src="https://github.com/hackclub/hack.af/assets/43505167/58e6ef65-afbc-4e58-9790-b33b87dc699d">

**Comment by DevIos01** [comment]
fixed, now it works

reason: Recent fix for #73, broke the SQL syntax which is now fixed and works fine 
result:
![image](https://github.com/hackclub/hack.af/assets/34939959/de300c0b-d233-4f00-988a-816294abb8cc)
