### ISSUE TITLE
Create new command to retrieve geolocation data for viewers of a slug

### ISSUE THREAD

**Issue by grymmy** [hackclub/hack.af#80]
Within hack.af's database, there is a Log table filled with geolocation data of people who have resolved the hack.af links.  We want a new command that will surface this information, and it should return all relevant data from the Log table.

This command should be admin-only, and it should create a log when it it is run that would be seen when using the /hack.af audit cmd...

**Comment by DevIos01** [comment]
Issue will be closed once #85 is merged!!
