### ISSUE TITLE
Fuzzy search

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack.af#81]
I'd like to look for hack.af entries like how I did on airtable, with a fuzzy search that goes over slugs and their destination. Currently the search feature only returns the exact slug I type in (which I could have already found by just going to hack.af/SLUG and seeing where it takes me), which is less useful.

**Comment by Santa116** [comment]
I agree that a fuzzy search covering both slugs and their destinations would enhance the user experience.

-Levenshtein Distance:
Calculate the Levenshtein distance between the user's input and each existing slug/destination pair.
Set a threshold for acceptable similarity, and return entries with distances below this threshold.

-Jaccard Similarity:
Tokenize slugs and destinations into n-grams (substrings of length n).
Calculate the Jaccard similarity between the user's input and each tokenized entry.
Return entries with Jaccard similarity above a specified threshold.

**Comment by maxwofford** [comment]
`/hack.af search bin`
`/hack.af search first-bin`
`/hack.af search bin-first`
`/hack.af search frc-bin`

<img width="397" alt="Screenshot 2024-04-23 at 12 21 08" src="https://github.com/hackclub/hack.af/assets/5891442/4e7744d6-421e-4124-8fa4-d46c82906d53">

I still can't find the slugs I'm looking for so I've been going into the production database to find them.

**Comment by grymmy** [comment]
/hack.af search bin should be returning a lot more results - agreed.  We definitely need to improve the search functionality here.

**Comment by grymmy** [comment]
@DevIos01 let's talk about how we should implement this in the near future

**Comment by DevIos01** [comment]
Hey @maxwofford, this is live https://github.com/hackclub/hack.af/pull/104 feel free to test it out. lmk if there any issue or if threshold should be lowered.

**Comment by maxwofford** [comment]
Nice work!
