### ISSUE TITLE
Printed result link is incorrectly formatted

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack.af#92]
<img width="714" alt="Screenshot 2024-04-13 at 22 22 10" src="https://github.com/hackclub/hack.af/assets/5891442/e40a8319-67fd-4850-ba04-94bf71d65df6">
<img width="773" alt="Screenshot 2024-04-13 at 22 23 01" src="https://github.com/hackclub/hack.af/assets/5891442/3689315d-299d-4137-bc04-4107124bbade">

**Comment by DevIos01** [comment]
With the latest changes for #93, the problem is fixed, feel free to reopen if it occurs.
