### ISSUE TITLE
unclear if i've taken a destructive action

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack.af#93]
<img width="711" alt="Screenshot 2024-04-13 at 22 23 37" src="https://github.com/hackclub/hack.af/assets/5891442/455addac-19f5-46ed-88f9-25e7fd101a48">

I just set this up and thought there wasn't anything at this link, but it says `changed` instead of `created`. Did I just overwrite another person's link?

**Comment by grymmy** [comment]
Please refer to the hack.af CLI documentation (default output of /hack.af).  You'll notice there is a history command, which shows the following:
<img width="810" alt="Screenshot 2024-04-24 at 8 45 24 AM" src="https://github.com/hackclub/hack.af/assets/43505167/8a75a13a-6c71-48de-b11d-cf4b3309f1ce">

So no, you didn't overwrite anyone else's link - and if you did make that mistake, you could correct it pretty easily.

That being said, marking this as a _feature request_.  Specifically, let's have the **confirmation text clearly differentiate between when slugs are modified vs. created**.

**Comment by grymmy** [comment]
@DevIos01 can u bang this one out?

**Comment by DevIos01** [comment]
The changes made from PR #97, fixes the problem, I have implemented a system that checks if it existed before and handles the message correctly, here is an example of how the response now looks:

![image](https://github.com/hackclub/hack.af/assets/34939959/775326f3-6ca6-4e47-848b-7ec0762fe28a)

**Comment by maxwofford** [comment]
<img width="466" alt="Screenshot 2024-04-25 at 12 26 02" src="https://github.com/hackclub/hack.af/assets/5891442/36305d45-bdf4-4be7-ad22-c6f6998a5178">

While testing I lost data. Given the screenshot, please tell me what the link I overwrote was.

**Comment by DevIos01** [comment]
Hey @maxwofford,

As @grymmy told before you can do `/hack.af help` to get all the list of commands you can use, to see the old history, you can use `/hack.af history *asdf*` and the result for the above was:

![image](https://github.com/hackclub/hack.af/assets/34939959/a48d3762-a183-48e5-a4c9-4ff0922961e6)

seems like u had made before with hackclub.com and now changed to hackclub.com/bin

feel free to reopen this issue if needed :)

**Comment by maxwofford** [comment]
I reopened the issue because this is needed. I'd like to get this for a creation action:

`Created! Now hack.af/asdf goes to hackclub.com.`

and this for an update:

`Updated! Now hack.af/asdf is switched from hackclub.com/old to hackclub.com/new.`

The current text is an improvement swapping out the 'update' and 'create' action, but I don't want to run 2 different tools when I do something, I want the 1 tool I run to pull the relevant data or me.

**Comment by DevIos01** [comment]
Hey @maxwofford,

I have made the changes as you requested and is [merged](https://github.com/hackclub/hack.af/pull/98), lmk if there anything else.

![image](https://github.com/hackclub/hack.af/assets/34939959/87cb6ee7-7e92-4270-877a-4a7c21c2a472)

**Comment by maxwofford** [comment]
This is great, thank you!
