### ISSUE TITLE
Show command that was run

### ISSUE THREAD

**Issue by maxwofford** [hackclub/hack.af#96]
I just searched for 5 different things. Here's my command history:

<img width="435" alt="Screenshot 2024-04-23 at 12 23 47" src="https://github.com/hackclub/hack.af/assets/5891442/67b14e0a-f7b7-4c61-bcc1-72ffd404db1c">

A nice UI enhancement would be to print out the command the user ran, like how orpheus prints it when I run `/airtable @msw`

<img width="346" alt="Screenshot 2024-04-23 at 12 24 28" src="https://github.com/hackclub/hack.af/assets/5891442/d163252d-8643-442f-84cc-85c969da7e2f">

**Comment by grymmy** [comment]
This seems very reasonable.

**Comment by maxwofford** [comment]
For example code that runs on hackclub/orpheus-bot: https://github.com/hackclub/orpheus-bot/blob/master/src/index.js#L238-L239
